// <auto-generated />
using System;
using LibraryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240916081238_Add description to model")]
    partial class Adddescriptiontomodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DateOfPublication")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "William Golding",
                            Available = true,
                            DateOfPublication = new DateOnly(2010, 8, 12),
                            Description = "Efter ett flyghaveri kastas en grupp pojkar mellan sex och tolv år iland på en liten ö i Söderhavet. De stiftar lagar, fördelar sysslorna och väljer anförare. Deras tillvaro kan bli paradisisk med rik tillgång på god mat, sol och fullständig frihet från de vuxnas tvång. Men snart tar leken en annan vänding: skräcken kryper över pojkarna, rivaliteten växer mellan ledarna. Det som kunde varit ett spännande sommarlovsäventyr blir en furiös hetsjakt där fruktan och grymhet slår fram och vägen mot undergång ligger utstakad.",
                            Genre = "Skönlitteratur",
                            ImageURL = "\\images\\flugornas-herre.jpg",
                            Title = "Flugornas herre"
                        },
                        new
                        {
                            ID = 2,
                            Author = "J R R Tolkien",
                            Available = true,
                            DateOfPublication = new DateOnly(2002, 1, 1),
                            Description = "Trilogin om Härskarringen - Sagan om ringen, Sagan om de två tornen och Sagan om konungens återkomst samlade i en upplaga.",
                            Genre = "Fantasy",
                            ImageURL = "\\images\\harskarringen.jpg",
                            Title = "Härskarringen"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Freida McFadden",
                            Available = false,
                            DateOfPublication = new DateOnly(2024, 3, 8),
                            Description = "Millie har avtjänat ett tioårigt fängelsestraff och bor i sin bil när hon får jobb som hembiträde hos den förmögna familjen Winchester: mamma Nina, pappa Andrew och nioåriga dottern Cecelia. Bostad ingår - ett minimalt vindsrum i familjens jättevilla.\r\nMillie satsar allt på att sköta jobbet perfekt - hon städar, tvättar, tar hand om parets dotter, lagar fantastiska middagar till familjen och äter själv ensam i vindsrummet. Men snart börjar hon ana att familjen Winchester döljer betydligt mörkare hemligheter än hon själv. ",
                            Genre = "Deckare",
                            ImageURL = "\\images\\hembitradet.jpg",
                            Title = "Hembiträdet"
                        },
                        new
                        {
                            ID = 4,
                            Author = "Gunilla Bergström",
                            Available = true,
                            DateOfPublication = new DateOnly(2006, 10, 30),
                            Description = "Pappa läser tidningen och vill inte leka med Alfons. \"Akta sågen\" säger han när Alfons drar fram verktygslådan. Alfons hamrar och spikar.",
                            Genre = "Barnbok",
                            ImageURL = "\\images\\aja-baja-alfons-aberg.jpg",
                            Title = "Aja baja, Alfons Åberg"
                        },
                        new
                        {
                            ID = 5,
                            Author = "Astrid Lindgren",
                            Available = false,
                            DateOfPublication = new DateOnly(2015, 4, 20),
                            Description = "Den allra första boken om Pippi Långstrump, den starkaste och snällaste och roligaste och rikaste flickan i hela världen. Hon bor alldeles ensam i Villa Villekulla med sin häst och sin apa Herr Nilsson. En hel kappsäck full med gullpengar har hon också. I huset bredvid bor Tommy och Annika, och sedan Pippi flyttade in har allt blivit mycket roligare! För Pippi bakar pepparkakor direkt på golvet, hon kan lyfta sin häst på rak arm och hon leker kull med poliser när de kommer och vill hämta henne till ett barnhem.",
                            Genre = "Barnbok",
                            ImageURL = "\\images\\pippi-langstrump.jpg",
                            Title = "Pippi Långstrump"
                        },
                        new
                        {
                            ID = 6,
                            Author = "Stephen King",
                            Available = false,
                            DateOfPublication = new DateOnly(2019, 9, 25),
                            Description = "På delstatsfängelset i Cold Mountain, i det cellblock som kallas Den gröna milen, väntar samvetslösa mördare på att dö fastspända i Gamla Gnisten, den elektriska stolen. De bevakas av härdade fängelsevakter som har sett sin beskärda del av brutalitet och omänsklighet. Men när fången John Coffey, dömd att dö för våldtäkt och mord på två minderåriga flickor, anländer på Den gröna milen förändras allt.",
                            Genre = "Skräck",
                            ImageURL = "\\images\\den-grona-milen.jpg",
                            Title = "Den gröna milen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
