// <auto-generated />
using System;
using LibraryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240910075844_update seed data")]
    partial class updateseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAPI.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DateOfPublication")
                        .HasColumnType("date");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "William Golding",
                            Available = true,
                            DateOfPublication = new DateOnly(2010, 8, 12),
                            Genre = "Skönlitteratur",
                            ImageURL = "\\images\\flugornas-herre.jpg",
                            Title = "Flugornas herre"
                        },
                        new
                        {
                            ID = 2,
                            Author = "J R R Tolkien",
                            Available = true,
                            DateOfPublication = new DateOnly(2002, 1, 1),
                            Genre = "Fantasy",
                            ImageURL = "\\images\\harskarringen.jpg",
                            Title = "Härskarringen"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Freida McFadden",
                            Available = false,
                            DateOfPublication = new DateOnly(2024, 3, 8),
                            Genre = "Deckare",
                            ImageURL = "\\images\\hembitradet.jpg",
                            Title = "Hembiträdet"
                        },
                        new
                        {
                            ID = 4,
                            Author = "Gunilla Bergström",
                            Available = true,
                            DateOfPublication = new DateOnly(2006, 10, 30),
                            Genre = "Barnbok",
                            ImageURL = "\\images\\aja-baja-alfons-aberg.jpg",
                            Title = "Aja baja, Alfons Åberg"
                        },
                        new
                        {
                            ID = 5,
                            Author = "Astrid Lindgren",
                            Available = false,
                            DateOfPublication = new DateOnly(2015, 4, 20),
                            Genre = "Barnbok",
                            ImageURL = "\\images\\pippi-langstrump.jpg",
                            Title = "Pippi Långstrump"
                        },
                        new
                        {
                            ID = 6,
                            Author = "Stephen King",
                            Available = false,
                            DateOfPublication = new DateOnly(2019, 9, 25),
                            Genre = "Skräck",
                            ImageURL = "\\images\\den-grona-milen.jpg",
                            Title = "Den gröna milen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
